// <auto-generated />
using System;
using ExampleLib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExampleLib.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250331134549_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ExampleLib.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Review")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author One",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 5,
                            Title = "Book One"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author Two",
                            PublishedDate = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 4,
                            Title = "Book Two"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author Three",
                            PublishedDate = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 3,
                            Title = "Book Three"
                        },
                        new
                        {
                            Id = 4,
                            Author = "George Orwell",
                            PublishedDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 5,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Harper Lee",
                            PublishedDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 5,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 6,
                            Author = "F. Scott Fitzgerald",
                            PublishedDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 4,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Herman Melville",
                            PublishedDate = new DateTime(1851, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 4,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Jane Austen",
                            PublishedDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 5,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Leo Tolstoy",
                            PublishedDate = new DateTime(1869, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 5,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.D. Salinger",
                            PublishedDate = new DateTime(1951, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 4,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 11,
                            Author = "J.R.R. Tolkien",
                            PublishedDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 5,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Ray Bradbury",
                            PublishedDate = new DateTime(1953, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 4,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Charlotte Brontë",
                            PublishedDate = new DateTime(1847, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = 5,
                            Title = "Jane Eyre"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
